### PR TITLE
feat: Kill electron process when Ctrl-C is triggered

### PR DESCRIPTION
**Pull request by Alecyrus**

### CODE REVIEW

**Comment by cawa-93** [comment]
Isn't that right now? The child process must end when the parent process ends.

**Comment by Alecyrus** [comment]
> Isn't that right now? The child process must end when the parent process ends.

When the web is a multi-page application with multiple BrowserWindows opened, if Ctrl-C is clicked, there is always one BrowserWindow left going blank and not exiting as expected.

**Comment by cawa-93** [comment]
What is your environment? Also please provide a repository where the problem is reproduced. I created an application that has several windows and all windows were successfully closed as expected on watch script stoped by `Ctrl+C`

**Comment by cawa-93** [comment]
You should check this issue again at the last commit. For now, I will close the PR without merging.

**Pull request closed without merging**
