### PR TITLE
feat: Add prettier support and reformat code with zero deps added

### PR DESCRIPTION
**Pull request by Tanimodori**
This is the zero-deps version pr of prettier support, see #821 for more info. This is the first stage of prettier support.

The `.prettierrc` file is ordered as official docs list does, and the missing `bracketSpacing` option is added. Some `eslint` and `tsconfig` JSON files are also reformatted.

The commit 3ed153da1ab8f192cebfc1f332054a68b8d1ad12 is done by running:

```
npx prettier --write "**/*.{vue,js,jsx,ts,tsx,json}"
```

Note that because prettier is not installed locally, so running command through `npx` requires a global install:

```
npm i -g prettier
```

However, it is recommended that install plugin in your IDE to contribute. The CLI is just for purely scripting use. See the "Using Prettier" section in #821 for more info.

### CODE REVIEW

**Comment by cawa-93** [comment]
If the goal is improve the dx for the contributors of this template, then I think it would cool to create an additional workflow with automatic code formatting for each PR:
1. Contributor makes changes with any formatting.
2. A workflow is launched that formats the code as required.
3. an additional commit with formatting changes is pushed to pr.

What do you think about it?

**Comment by Tanimodori** [comment]
The practical formatting methods as far as I know are:

| Method | Effects | Deps |
| --- | --- | --- |
| Nothing | Manual control | Zero |
| `.EditorConfig` | Weak recommendation | Zero |
| `.prettierrc` | Strong recommendation | Zero |
| `prettier` in `.lint-staged` | Force format on save, skippable* | `prettier` |
| `prettier` in `eslint` | Format check, unskippable* | `eslint-prettier-plugin` and <br> `eslint-prettier-config` |

\* `git commit ----no-verify` can be used to skip. But the CI test will fail.

If you want to make it a force check for prs, I recommend the `eslint` approach. With zero deps, the 
`.prettierrc` is better than `.EditorConfig`.

**Comment by Tanimodori** [comment]
Sorry for the mess wrong local branch. Will reopen later.

**Comment by Tanimodori** [comment]
Ok, I'll open a pr soon

**Pull request closed without merging**
