### PR TITLE
Setup for vscode

### PR DESCRIPTION
**Pull request by udondan**
This adds basic setup and plugin recommendation for Visual Studio Code.

When starting with this template I found two problems:

1. All .vue files threw errors:

   ```
   Parsing error: Cannot find module '@typescript-eslint/parser'
   ```
   
   vscode error

   This is triggered by the ESLint extension.

   Therefore this missing package is added to the dev dependencies.

2. When using the Vetur extension, the default configuration has conflicting formatting settings with the ESLint config. Whenever you saved a .vue file, eslint would complain about the automatically formatted result. Therefore this change adds a default setting which aligns with what eslint expects.

Finally, the extensions [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) and [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) are recommendet to the user, if they're not installed.

### CODE REVIEW

**Comment by cawa-93** [comment]
1. `@typescript-eslint/parser` Should be installed automatically as peer dependency by npm v7 feature. Do you ensure this is template but not extension bug? Does `npm run lint` works it terminal without installing `@typescript-eslint/parser` manually?
2. I agree to change the Vetur settings. cc: @xiaohulu
3. As for extensions and their recommendations. How does it work? Remember that this template is not just for Vue. Wouldn't it be noisy for projects on other frameworks? Instead of Vetur, I would recommend [Volar](https://github.com/johnsoncodehk/volar), as this is what [Vue himself recommends](https://v3.vuejs.org/api/sfc-tooling.html#ide-support).

**Comment by udondan** [comment]
1. Indeed, `npm run lint` is failing as well. Didn't see that before. So it's not only a problem in VSCode with that etension.
 
   When I freshly clone this project and run `npm i` and `npm run lint`:

   ```
   $ npm run lint
   
   > lint
   > eslint . --ext js,ts,vue
   
   
   Oops! Something went wrong! :(
   
   ESLint: 7.32.0
   
   Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/parser'
   Require stack:
   - /private/tmp/x/three/.eslintrc.json
       at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
       at Function.resolve (node:internal/modules/cjs/helpers:100:19)
       at Object.resolve (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
       at ConfigArrayFactory._loadParser (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/config-array-factory.js:929:45)
       at ConfigArrayFactory._normalizeObjectConfigDataBody (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/config-array-factory.js:724:43)
       at _normalizeObjectConfigDataBody.next (<anonymous>)
       at ConfigArrayFactory._normalizeObjectConfigData (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
       at _normalizeObjectConfigData.next (<anonymous>)
       at ConfigArrayFactory.loadInDirectory (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
       at CascadingConfigArrayFactory._loadConfigInAncestors (/private/tmp/x/three/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
   ```
   
   After installation of the package this works. 
   
   npm is version 7.21.1 on MacOS.

2. I guess this is obsolete, when changing the extension.

3. Good points. I'll have a look at the Volar extension. Generally the recommendations work like [this](https://tattoocoder.com/recommending-vscode-extensions-within-your-open-source-projects/ ) - So the user of course can ignore them. I believe VSCode is so clever to only recommend them once. I have not ever seen this popup, even when the extensions are not installed. I only see them when I manually navigate to the extensions panel and open the "workspace recommended extensions".

**Comment by cawa-93** [comment]
1. Hmm.... Maybe you some how change npm config. What `npm config get legacy-peer-deps` show?
3. Move please recommendations for Volar to separate PR.

**Comment by udondan** [comment]
Indeed, I have legacy-peer-deps set to true, since I need this in many other projects. OK, now I understand why the package was missing. Then let me just close this :)

**Pull request closed without merging**
