### PR TITLE
feat: Add prettier support and reformat code.

### PR DESCRIPTION
**Pull request by Tanimodori**
**Summary**
This pr add prettier support and does not intend to change any functions.

[Prettier](https://prettier.io/) is an automatic formatter for many languages including JavaScript and TypeScript. It is now widely used in frontend projects to keep the devs focusing on programming rather than maintaining code formats, which saves time and allows effective collaboration. This repo is already have an EditorConfig but it is not as powerful as prettier is so I want to push it even further.

**`eslint` Integration**
Deps like `eslint-config-prettier` and `eslint-plugin-prettier` allows prettier to further integration with `eslint`, since this project is already have an lint-staged check, it will make sure all submitted code must be formatted in the same way.

**The Chosen Style & Limitations**
I tried as much as I can to keep the original coding style reflected in prettier config (`.prettierrc`), but there are still limitations beyond the capability of prettier now.

Here's are styles kept:

* `"semi": true` leaves semicolons at end of lines.
* `"vueIndentScriptAndStyle": false` leaves no indent at Vue SFC's `<script>` and `<style>` blocks.
* `"singleAttributePerLine": true` leaves only one attribute per line at `<template>` blocks.
* `"singleQuote": true` forces to use single quotes, but nested quotes will be double quotes. This is explained at pr #815.
* `"arrowParens": "avoid"` avoids parens at arrow functions.
* `"trailingComma": "all"` forces trailing commas.
* `"htmlWhitespaceSensitivity": "strict"` keeps strict html whitespace consistency while formatting. Some formatted code seems ugly (see 6459e5e6cac893c49fcbb3784a064b50c4a9af8c) which is actually prettier trying to keep the consistency. You can either edit manually to change whitespace outcome to get a better-looking code or wrap them with `<span>` to keep it. There are some tests in the project which requires whitespace consistency (see `packages\renderer\tests\ElectronVersions.spec.ts`). If the consistency is not important, 'ignore' option is best to make code looks better.
* `"endOfLine": "lf"` keeps the EOL the same as the EditorConfig does.

... And the limitations:

* The [html void elements](https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#syntax-elements) such as `<br>`, `` and `<input>` WILL ends with `/>`. But it should be okay since [it is still valid HTML5 code](https://stackoverflow.com/a/21898502). More info at https://github.com/prettier/prettier/issues/5246
* [Some eslint rules](https://github.com/prettier/eslint-config-prettier/blob/main/index.js) cannot be used or only used with limitations alongside with prettier. But it is normally ok because much of those are taken care by prettier.

**Using Prettier**

Check [prettier docs](https://prettier.io/docs/en/editors.html) for finding plugins for your editor. Afaik popular editors like VSCode and JetBrains IDEs are supported. Or [use prettier via its CLI](https://prettier.io/docs/en/cli.html). The commit 89eccb7e817b780951282cc6fb17152045e40517 is done by running the following command:

```
npx prettier --write "**/*.{vue,js,jsx,ts,tsx}"
```

In this case prettier will read config found at currend folder (`.prettierrc` and `.prettierignore`) and format all files matching pattern `**/*.{vue,js,jsx,ts,tsx}` except those ignored in `.prettierignore`.

### CODE REVIEW

**Comment by cawa-93** [comment]
Thank you. You have done a really great job.
But I'm not sure that adding the prettier is necessary. Actually, I was thinking about removing eslint.

In my opinion, the _template_ should remain minimal and flexible. I try to add as less dependencies as possible so that each user can configure his project as he needs. The boilerplate should remain a template with some missing features, rather than being overloaded with all the features in the world.

Does everyone need eslint? Does everyone need a prettier? Is it easier to add the prettier manually or to remove it? Maybe I'm wrong. I must think about it. For now, I'll leave it unmerged with the RFC mark. Maybe someone in the community has some thoughts

**Comment by Tanimodori** [comment]
Thanks for your appreciation. Those questions you asked are really all good questions to define the repository. And actually I don't think this pr will be merged quickly because I know these questions had to be answered. So please let me answer them for your infomation. I hope these answers can help you decide.

### Is a feature like `prettier`, `eslint` and `tailwindcss` necessary?

It is hard to tell which feature is necessary **for everyone**, but it is simple **for a particular user**. Vue CLI have [an interactive interface](https://cli.vuejs.org/guide/creating-a-project.html#vue-create) to choose which feature will be included in the template when they use the template. I haven't take a look at how it implements but it's definitely the future.

### What is philosophy of a template? minimal? flexible? 

It really depends on which position you want to take in the ecosystem. Some toy templates features minimal, but there are also heavy templates meant to be secure and production-ready. 

For me, I choose this template because it uses Vite, Electron and Typescript, and it's secure, modern and production-ready. There are way too many templates that are Webpack-based, JavaScript-based, insecure or out-of-date. The [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) is a much simpler template that it have simpler build, watch facility, simpler folder structure which makes it good for new-comers. But it is insecure because it runs with `nodeIntegration` enabled and `contextIsolation` disabled. It does not have `eslint` as you wish and no tests. Over all it is a template meant to be simple but not production-ready in the ecosystem.

It is a kind of balance or choice but as I mentioned above, a fixed template has to choose but if users can choose features, it can be both minimal and production-ready at users' choice.

### Is it easier to add the prettier manually or to remove it?

Prettier is kind of TypeScript. All prettier-formatted codes are valid JS/TS codes. Removing can be done by just remove deps in https://github.com/cawa-93/vite-electron-builder/pull/821/commits/6504fd3c68e702c3357767075a612b6a4dae8a99 and in eslint config https://github.com/cawa-93/vite-electron-builder/pull/821/commits/ae4528d20c1cf2c9500802b5f8fdcb9371d26b7d as how I added it. The point here is to keep the code at this repository prettier-compatible so if one installs prettier, they don't need to format them again and get prettier working instantly. If they don't install, the prettier plugin itself is wiped out as the type space of TypeScript leaving the remaining template still works (in case that user can choose features). Prettier also make collaboration of this repository easier so that we don't need to worry about code formats.

If you are really worry about dep inflates and want zero deps, you can remove `prettier` from deps and eslint config, but leaves prettier config and ignores. As long as your editor has a prettier plugin, it will read those config and keep the style consistent. And turn off rules that prettier is conflicting to eslint config manually as `eslint-config-prettier` does.

**Comment by Tanimodori** [comment]
My tests current conflicting rules are just `vue/html-self-closing` and `vue/singleline-html-element-content-newline`. Disabling them is not a big harm I think. So it is a quick fix.

```
PS path\to\vite-electron-builder> npm run lint

> lint
> eslint . --ext js,ts,vue

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

=============

path\to\vite-electron-builder\packages\renderer\src\App.vue
   8:3   warning  Disallow self-closing on HTML void elements (<img/>)  vue/html-self-closing
  15:74  warning  Disallow self-closing on HTML void elements (<br/>)   vue/html-self-closing

path\to\vite-electron-builder\packages\renderer\src\components\ReactiveCounter.vue
  8:28  warning  Expected 1 line break after opening tag (`<button>`), but no line breaks found    vue/singleline-html-element-content-newline
  8:50  warning  Expected 1 line break before closing tag (`</button>`), but no line breaks found  vue/singleline-html-element-content-newline
  9:3   warning  Disallow self-closing on HTML void elements (<br/>)                               vue/html-self-closing
  9:9   warning  Disallow self-closing on HTML void elements (<br/>)                               vue/html-self-closing

path\to\vite-electron-builder\packages\renderer\src\components\ReactiveHash.vue
  15:5  warning  Disallow self-closing on HTML void elements (<input/>)  vue/html-self-closing
  20:3  warning  Disallow self-closing on HTML void elements (<br/>)     vue/html-self-closing
  23:5  warning  Disallow self-closing on HTML void elements (<input/>)  vue/html-self-closing
  29:3  warning  Disallow self-closing on HTML void elements (<br/>)     vue/html-self-closing
  29:9  warning  Disallow self-closing on HTML void elements (<br/>)     vue/html-self-closing

✖ 11 problems (0 errors, 11 warnings)
  0 errors and 11 warnings potentially fixable with the `--fix` option.
```

**Comment by Tanimodori** [comment]
Oh I missed out a `bracketSpacing` option. I'll add it back later.

**Comment by Tanimodori** [comment]
The create script is basically a nodejs script. The one of vue-cli is [here](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli/lib/Creator.js)

**Comment by Fractal-Tess** [comment]
To a certain degree, I agree with both of you.
On one side, I believe that eslint/prettier are extremely easy to leave for the user to configure and add as per their needs.
Not everyone writes in the same format and style as everyone else (spacing, commas, semicolons, arrow parens, and others).
On the other hand I found it burdensome to make changes on the sourcode when I was making my PRs. My vs-code would automatically format the files with the prettier vs-code extension, overwriting the original spacing, quotes, and overall structure.
Personally, I'm +1 for prettier.

**Comment by Tanimodori** [comment]
@Fractal-Tess In short:

Do *we* need prettier for the codebase? *--Yes.*

Do *users* need prettier for their codebase? *--It depends.*

**Comment by Tanimodori** [comment]
Give me some time to make a scaffolding script. Before that I can draft a quick, zero deps prettier fix as mentioned above.

**Comment by Tanimodori** [comment]
I've been working on a scaffolding tool for `vite-electron-builder` at [Tanimodori/generator-vite-electron-builder](https://github.com/Tanimodori/generator-vite-electron-builder) using yeoman. Currently the inquire function is completed which looks good and promising.

Code_nTVI8g1YG5

This tools currently does nothing other than inquiring. You can run `npm run test` to play with it.

**Comment by caoxiemeihao** [comment]
Most of the time, the boilerplate project of the Electron + Vite class is more like a supplement to the official Vite template. Too many features can be unfriendly to newbies.

**Comment by Tanimodori** [comment]
@caoxiemeihao [`electron-vite-vue`](https://github.com/electron-vite/electron-vite-vue) is a great repository for demonstrating how electron works for new-comers. When I started learning Electron I learned a lot from it. Thanks for your contribution. <3

As what I've said, there are new-comers who want a simple repository as well as those who want a production-ready one. Combined we can achieve a complete ecosystem.

**Comment by cawa-93** [comment]
Resolved in https://github.com/cawa-93/vite-electron-builder/pull/831

**Pull request closed without merging**
